<template>
	<tr class="download-item" :class="nested ? 'subitem' : ''" @click="toggleChildren">
		<td class="show-icon-container">
			<!-- empty slot rendered if there's only a single download -->
			<v-icon v-if="!nested && !single" :icon="showIcon" size="x-small" class="show-icon" />
		</td>
		<td class="download-details">
			<span class="download-name">
				<download-badge dot :badge="labelColor" />
				<span class="mx-1 my-1">{{ labelText }}</span>
			</span>
			<download-badge badge="version">{{ version }}</download-badge>
			<download-badge v-if="item.latest" badge="latest">Latest</download-badge>
			<!-- avoid SSR warning with date localization -->
			<span class="mobile-details" :title="exact">
				{{ relative }}
			</span>
		</td>

		<td class="date cursor-help">
			<v-tooltip location="top">
				<template #activator="{ props }">
					<span v-bind="props">{{ relative }}</span>
				</template>
				{{ exact }}
			</v-tooltip>
		</td>

		<!-- for some reason styling td causes problems -->
		<td>
			<div class="links">
				<nuxt-link
					v-for="(link, linkType) in item.links"
					:key="link"
					class="btn btn-secondary btn-dl"
					:to="link"
					:aria-label="`${textFormat[linkType]} download for ${labelText} (${version})`"
				>
					<media-icon class="dl-icon" :icon="linkType" fallback="download" />
					<span class="link-text ml-2">{{ textFormat[linkType] || linkType }}</span>
				</nuxt-link>
			</div>
		</td>
	</tr>
</template>

<script>
import MediaIcon from "~/components/lib/media-icon.vue";
import DownloadBadge from "./download-badge.vue";

export default defineNuxtComponent({
	name: "download-line",
	components: {
		MediaIcon,
		DownloadBadge,
	},
	props: {
		nested: {
			type: Boolean,
			required: false,
			default: false,
		},
		single: {
			type: Boolean,
			required: false,
			default: false,
		},
		item: {
			type: Object,
			required: true,
		},
		curse: {
			type: Object,
			required: false,
			default: null,
		},
		version: {
			type: String,
			required: true,
		},
	},
	emits: ["toggle"],
	data() {
		return {
			isOpen: false,
			textFormat: {
				download: "Download",
				curse: "Curse",
				github: "GitHub",
				modrinth: "Modrinth",
				mcpedl: "MCPEDL",
			},
			labelColors: {
				GitHub: "github",
				Release: "green",
				"Pre-release": "blue",
				Beta: "yellow",
				Alpha: "orange",
				Snapshot: "gray",
			},
			// prevents potential hydration mismatch when used in computed
			dateNow: Date.now(),
		};
	},
	methods: {
		toggleChildren() {
			// handle icon change then pass back to download-version to unhide children
			this.isOpen = !this.isOpen;
			this.$emit("toggle");
		},
	},
	computed: {
		showIcon() {
			return this.isOpen ? "mdi-minus" : "mdi-plus";
		},
		labelText() {
			// display names override any autogenerated names
			if (this.item.file_name) return this.item.file_name;

			if (!this.item.file_version) return this.item.file_type;
			return `${this.item.file_type} ${this.item.file_version}`;
		},
		labelColor() {
			return this.labelColors[this.item.file_type] || "green";
		},
		date() {
			if (this.item.date === "rolling") return this.dateNow;
			if (this.item.date) return this.item.date;

			if (this.curse && this.curse.uploaded_at) return this.curse.uploaded_at.split("T")[0];

			// no other way to get dates
			return null;
		},
		exact() {
			if (this.date === null) return "Unknown";
			return exactDate(this.date);
		},
		relative() {
			if (this.date === null) return "Unknown";
			return relativeDate(this.date);
		},
	},
});
</script>

<style scoped lang="scss">
@use "~/assets/css/variables" as *;

$item-highlight: rgba(255, 255, 255, 0.05);

td {
	color: $text-card;
	text-align: center;
	// for some reason you can't pad <tr> tags directly, so we style the children instead
	padding: 0.2rem 0px;

	// https://dev.to/temmietope/rounded-edges-on-table-rows-1d0n
	&:first-child {
		border-radius: $border-radius 0 0 $border-radius;
		padding-left: calc($padding-card / 2);
	}
	&:last-child {
		border-radius: 0 $border-radius $border-radius 0;
		padding-right: calc($padding-card / 2);
	}
}

.download-item {
	transition: $transition-button;
	&:hover {
		background: $item-highlight;
	}
}

.subitem {
	// kinda lazy way of showing old downloads as less significant
	// todo: do this better lol
	opacity: 75%;
}

// match intrinsic card padding on left side (looks more proportional)
.show-icon-container {
	padding-right: $padding-card;
}

.show-icon {
	// less opaque
	color: $text-navigation;
	cursor: pointer;
}

.download-details {
	text-align: left;
	width: 100%;
	* {
		margin-right: 0.3rem;
	}
}

// fix for stretched dots
.download-name {
	display: inline-flex;
	align-items: center;
}

.date {
	white-space: pre;
	padding: 0 2rem;
}
.mobile-details {
	display: none;
}

.links {
	// for some reason flex doesn't fill the whole td by default
	width: 100%;
	height: 100%;
	display: inline-flex;
	align-items: center;
	justify-content: center;
	gap: 0.75rem;
}

// small buttons, uniform width for nicer table layout
.btn-dl {
	padding: 0.1rem;
	width: 120px;
}

i.dl-icon {
	font-size: 20px;
}

@media screen and (max-width: $breakpoint-md) {
	// reduce gap, align to right since centering icon buttons looks bad
	.links {
		gap: 0.5rem;
		justify-content: end;
	}

	// square icon buttons
	.btn-dl {
		width: 2rem;
		height: 2rem;
	}
	.link-text {
		display: none;
	}
}

@media screen and (max-width: $breakpoint-sm) {
	// remove inline so it wraps the badges underneath (really stupid hack)
	.download-name {
		display: flex;
	}

	// hide desktop details and show mobile details
	.date {
		display: none;
	}
	.mobile-details {
		display: block;
	}

	// remove hover effect (looks bad on mobile)
	.download-item:hover {
		background: transparent;
	}

	// align icon to download name (looks better than in the middle)
	.show-icon-container {
		vertical-align: top;
	}
}
</style>
